### ISSUE TITLE
Parsing bug

### ISSUE THREAD

**Issue by philip-nicholls** [danielgindi/node-csv-reader#27]
test.csv
```
"A", "1"
"2", "B"
"C", "D"

```

parse.js
```
let inputStream = fs.createReadStream(__dirname + '/test.csv', 'utf8');
inputStream
    .pipe(new CsvReadableStream())
    .on('data', function (row) {
        console.log("DATA", row);
    })
    .on('end', function () {
        console.log("END");
    })
    .on('error', function (e) {
        reject(e);
    });
```

Output
```
DATA [ 'A', ' "1"' ]
DATA [ '2', ' "B"' ]
DATA [ 'C', ' "D"' ]
END
```

Your parser doesn't like whitespace between the columns.

**Comment by yeya** [comment]
I guess Microsoft Excel "doesn't like" it too.
It reads your test.csv just the same...
![image](https://user-images.githubusercontent.com/6382246/158081860-717f95a1-a27f-48de-9a5d-bce2cc7629d1.png)

What do you think should be the result, and why?

**Comment by danielgindi** [comment]
This parser behaves like Excel, right, but it is only because this is the correct behavior. Other behaviors would create unpredictable results.
This is a comma separated file, not "comma and space separated".
Now when there are special characters, we need to put the value in quotes.
And quotes could appear inside a value. 
Imagine a value that begins with a space and a quote... That's just a standard value, unwrapped.
Btw, I have never seen any piece of software create csvs with spaces after the commas.
